
package ventanas;

import excepciones.NoSePuedeException;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import tpboris.AdministradorDeConexiones;
import tpboris.Cajero;
import tpboris.Usuario;
import tpboris.Util;

/**
 *
 * @author Bor
 */
public class PantExtraccion extends javax.swing.JFrame {
    
    PantMenu menu;

    public PantExtraccion(PantMenu menu) {
        this.menu=menu;
        initComponents();
        this.mensjError.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitulo = new javax.swing.JLabel();
        lbMensaje = new javax.swing.JLabel();
        tfNumero = new javax.swing.JTextField();
        mensjError = new javax.swing.JLabel();
        btEntrar = new javax.swing.JButton();
        btVolver = new javax.swing.JButton();
        btSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(640, 480));

        lbTitulo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitulo.setText("Extraccion");
        lbTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbMensaje.setFont(new java.awt.Font("Tahoma", 0, 34)); // NOI18N
        lbMensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbMensaje.setText("Digite la cantidad a retirar, por favor");

        tfNumero.setFont(new java.awt.Font("Tahoma", 0, 34)); // NOI18N
        tfNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfNumeroKeyPressed(evt);
            }
        });

        mensjError.setFont(new java.awt.Font("Tahoma", 2, 34)); // NOI18N
        mensjError.setForeground(new java.awt.Color(255, 0, 0));
        mensjError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mensjError.setText("Error, ingrese una cantidad valida.");
        mensjError.setFocusable(false);

        btEntrar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btEntrar.setText("Entrar");
        btEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEntrarActionPerformed(evt);
            }
        });

        btVolver.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btVolver.setText("Volver");
        btVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVolverActionPerformed(evt);
            }
        });

        btSalir.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btSalir.setText("Salir");
        btSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btVolver, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
                    .addComponent(btSalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
                    .addComponent(btEntrar, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
                    .addComponent(lbMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
                    .addComponent(mensjError, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
                    .addComponent(tfNumero, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lbTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(lbMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(33, 33, 33)
                .addComponent(tfNumero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mensjError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btEntrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btVolver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(45, 45, 45)
                    .addComponent(lbTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(381, 381, 381)))
        );

        lbMensaje.getAccessibleContext().setAccessibleName("Transferencia");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVolverActionPerformed
        //clic en "volver"
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btVolverActionPerformed

    private void btSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalirActionPerformed
        //clic en "salir"
        this.dispose();
        menu.dispose();
        JFrame nuevoBienvenida = new PantBienvenida(false);
        JOptionPane.showMessageDialog(null,"Gracias por usar los cajeros 'dolar 30 pe'");
        nuevoBienvenida.setVisible(true);
    }//GEN-LAST:event_btSalirActionPerformed

    private void btEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEntrarActionPerformed
        //clic en "entrar"
        System.out.println("Entrar - Extraccion");//sacar
        //primero reseteo el mensaje de error y el textField
        this.mensjError.setVisible(false);
        String strEfectivo = this.tfNumero.getText();
        this.tfNumero.setText("");
        System.out.println("strEfectivo "+strEfectivo);//sacar

        //validar que se ingreso un numero
        if (Util.validarEfectivo(strEfectivo)){
            System.out.println("el efectivo ingresado puede ser convertido a double");//sacar

            //parsear
            double doubEfectivo = Double.parseDouble(strEfectivo);
            Usuario user = menu.getUser(); //el user
            Connection conexion = null;
            
            try{
                
                conexion = AdministradorDeConexiones.obtenerConexion();

                //si el user tiene la cantidad que quiere extraer y si el cajero la tiene, ademas que sea multiplo de 20
                if (user.tieneSuficiente(doubEfectivo) && Cajero.validarEfectivoCajero(doubEfectivo)){
                    
                    //saldoUpdate tiene que ser como maximo el stock del cajero, se lleva todo lo que hay en el cajero
                    //saldoUpdate tiene que ser como minimo 0, o sea el user saca toda la guita que tiene en su cuenta
            
                    double saldoAnterior = user.solicitarSaldo();
                    System.out.println( "saldoAnterior(user) "+saldoAnterior);//sacar
                    double saldoUpdate = saldoAnterior-doubEfectivo;//se resta porque es una extraccion
                    System.out.println( "saldoUpdate "+saldoUpdate);//sacar
                    
                    double efectivoAnterior = Cajero.obtenerEfectivoDisponible();
                    System.out.println( "efectivoAnterior(Cajero) "+efectivoAnterior);//sacar
                    double efectivoUpdate = efectivoAnterior-doubEfectivo; //se resta porque es una extraccion
                    System.out.println( "EfectivoUpdate "+efectivoUpdate);//sacar
                    
                    //conectarme y hacer transferencia
                    //hago una trasaccion porque hay que cambiar la cuenta del usuario y el contenido del cajero a la vez
                    
                    conexion.setAutoCommit(false);
                    //cambio el saldo del usuario
                    user.setSaldo(saldoUpdate);//si esto se hizo, entonces repercute en el monto del cajero
                    //cambio el efectivo del cajero
                    Cajero.setEfectivo(efectivoUpdate);

                    conexion.commit();

                    JOptionPane.showMessageDialog(null,"Extraccion realizada con exito! \nRecibiste $"+doubEfectivo+"\nAun te quedan $"+user.solicitarSaldo()+" en tu cuenta");
                    
                }else{
                    JOptionPane.showMessageDialog(null,"La transaccion no pudo ser realizada!");
                    System.out.println("user no tiene sufieciente plata o el cajero no tiene stock o no es %20");//sacar
                    //llega aca alguna vez?????? No.
                }
            
            }catch(NoSePuedeException exPropia){
                
                JOptionPane.showMessageDialog(null,exPropia.getMessage());
                
            }catch (ReflectiveOperationException | SQLException ex) {

                try {
                    
                    if(conexion != null){
                        conexion.rollback();
                    }
                } catch (SQLException ex1) {}
                JOptionPane.showMessageDialog(null,"La transaccion no pudo ser realizada");
                
            }finally{
                //cerrar
                try {

                    if(conexion != null){
                        conexion.close();
                    }

                }catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null,"La transaccion no pudo ser realizada");
                }
            }

        }else{
            System.out.println("ingreso erroneo (se ingreso algo que no puede ser Double o es negativo)");//sacar
            //pongo mensaje de error en la pantalla.
            this.mensjError.setVisible(true);
        }
        
        System.out.println("fin enviar Extraccion!");//sacar
    }//GEN-LAST:event_btEntrarActionPerformed

    private void tfNumeroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNumeroKeyPressed
        // si se presiona ENTER que se ejecute lo que pasa cuando toco enviar
        if (evt.getKeyCode() == 10) {
            this.btEntrarActionPerformed(null);
        }
    }//GEN-LAST:event_tfNumeroKeyPressed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEntrar;
    private javax.swing.JButton btSalir;
    private javax.swing.JButton btVolver;
    private javax.swing.JLabel lbMensaje;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JLabel mensjError;
    private javax.swing.JTextField tfNumero;
    // End of variables declaration//GEN-END:variables
}
