
package ventanas;

import excepciones.NoSePuedeException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Bor
 */
public class PantSaldo extends javax.swing.JFrame {
    
    PantMenu menu;

    public PantSaldo(PantMenu menu) {
        this.menu=menu;
        initComponents();
        
        try {
            double saldo = menu.getUser().solicitarSaldo();
            
            this.lbSaldo.setText(Double.toString(saldo));
        }catch (NoSePuedeException e){
            //error
            this.lbMensaje.setText("");
            this.lbSaldo.setFont(new java.awt.Font("Tahoma", 2, 28));
            this.lbSaldo.setForeground(new java.awt.Color(255, 0, 0));
            this.lbSaldo.setText("Error en el sistema, intente de nuevo mas tarde.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbMensaje = new javax.swing.JLabel();
        lbSaldo = new javax.swing.JLabel();
        btVolver = new javax.swing.JButton();
        btSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(640, 480));

        lbMensaje.setFont(new java.awt.Font("Tahoma", 0, 34)); // NOI18N
        lbMensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbMensaje.setText("Su saldo es ");

        lbSaldo.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lbSaldo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btVolver.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btVolver.setText("Volver");
        btVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVolverActionPerformed(evt);
            }
        });
        btVolver.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btVolverKeyPressed(evt);
            }
        });

        btSalir.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btSalir.setText("Salir");
        btSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
                    .addComponent(lbSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
                    .addComponent(btVolver, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
                    .addComponent(btSalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(lbMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(56, 56, 56)
                .addComponent(lbSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104)
                .addComponent(btVolver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVolverActionPerformed
        //clic en "volver"
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btVolverActionPerformed

    private void btSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalirActionPerformed
        //clic en "salir"
        this.dispose();
        menu.dispose();
        JFrame nuevoBienvenida = new PantBienvenida(false);
        JOptionPane.showMessageDialog(null,"Gracias por usar los cajeros 'dolar 30 pe'");
        nuevoBienvenida.setVisible(true);
    }//GEN-LAST:event_btSalirActionPerformed

    private void btVolverKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btVolverKeyPressed
        if (evt.getKeyCode() == 10) {
            this.btVolverActionPerformed(null);
        }
    }//GEN-LAST:event_btVolverKeyPressed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSalir;
    private javax.swing.JButton btVolver;
    private javax.swing.JLabel lbMensaje;
    private javax.swing.JLabel lbSaldo;
    // End of variables declaration//GEN-END:variables

    private static class NoMultiploVeinteException extends RuntimeException {

        public NoMultiploVeinteException() {
            JOptionPane.showMessageDialog(null,"El cajero solo maneja billetes de 20, elija un monto multiplo de 20");
        }
    }
}
