
package ventanas;

import excepciones.ErrorDatabaseException;
import excepciones.UsuarioNoExisteException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import tpboris.Usuario;
import tpboris.Util;

/**
 *
 * @author BOR
 */
public class PantAutentificacion extends javax.swing.JFrame {
    
    private String strCuenta;

    PantAutentificacion(String cuenta) {
        this.strCuenta=cuenta;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfNumero = new javax.swing.JTextField();
        btEntrar = new javax.swing.JButton();
        btBorrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(640, 480));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        tfNumero.setFont(new java.awt.Font("Tahoma", 0, 34)); // NOI18N
        tfNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfNumeroKeyPressed(evt);
            }
        });

        btEntrar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btEntrar.setText("Entrar");
        btEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEntrarActionPerformed(evt);
            }
        });

        btBorrar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btBorrar.setText("Borrar");
        btBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBorrarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 34)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ingrese su NIP, por favor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
                    .addComponent(btBorrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btEntrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfNumero, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jLabel1)
                .addGap(78, 78, 78)
                .addComponent(tfNumero)
                .addGap(110, 110, 110)
                .addComponent(btEntrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBorrarActionPerformed
        //clic en "Borrar"
        this.tfNumero.setText("");
    }//GEN-LAST:event_btBorrarActionPerformed

    private void btEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEntrarActionPerformed
        //clic en "entrar"
        String strNip = this.tfNumero.getText();
        
        if (Util.validarIngreso(strCuenta) && Util.validarIngreso(strNip)){
            System.out.println("Autentificacion - Campos Validados");//sacar
            //parsear            
            int intCuenta = Integer.parseInt(strCuenta);
            int intNip = Integer.parseInt(strNip);

            //conectarme y validar el usuario en bd
            try {
                Usuario user = Usuario.validarCredenciales(intCuenta, intNip);
                //mandar a pantalla Menu con usuario
                JFrame menu = new PantMenu(user);
                menu.setVisible(true);
                System.out.println("Autentificacion - Usuario Validado y creado");//sacar
            } catch (UsuarioNoExisteException ex) {
                //volver a bienvenida con pantalla de error.
                JFrame bienvenidaError = new PantBienvenida(true);
                bienvenidaError.setVisible(true);
            } catch (ErrorDatabaseException ex) {
                JOptionPane.showMessageDialog(null,ex.getMessage());
                //volver a bienvenida con pantalla de error.
                JFrame bienvenidaError = new PantBienvenida(true);
                bienvenidaError.setVisible(true);
            }

        }else{
            System.out.println("Autentificacion - Campos ingresados Invalidos");//sacar
            //volver a bienvenida con pantalla de error.
            JFrame bienvenidaError = new PantBienvenida(true);
            bienvenidaError.setVisible(true);
        }
        
        this.dispose();
    }//GEN-LAST:event_btEntrarActionPerformed

    private void tfNumeroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNumeroKeyPressed
        // si se presiona ENTER que se ejecute lo que pasa cuando toco enviar
        if (evt.getKeyCode() == 10) {
            this.btEntrarActionPerformed(null);
        }
    }//GEN-LAST:event_tfNumeroKeyPressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // si se presiona ENTER que se ejecute lo que pasa cuando toco enviar
        if (evt.getKeyCode() == 10) {
            this.btEntrarActionPerformed(null);
        }
    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBorrar;
    private javax.swing.JButton btEntrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField tfNumero;
    // End of variables declaration//GEN-END:variables

}
